export const gomemNameList = [
  "곽춘식",
  "권민",
  "길햇님송이",
  "김치만두번영택사스가",
  "노스페라투 호드",
  "단답벌레",
  "도파민박사",
  "독고혜지",
  "뢴트게늄",
  "부정형인간",
  "미츠네 하쿠",
  "비밀소녀",
  "비즈니스킴",
  "새우튀김",
  "소피아",
  "왁파고",
  "이덕수 할아바이",
  "카르나르 융터르",
  "캘리칼리 데이비슨",
  "풍신",
  "프리터",
  "해루석",
  "히키킹"
];

export enum GomemNames {
  kwakChunSik = "곽춘식",
  kwonmin = "권민",
  jururu = "길햇님송이",
  kimchimandu = "김치만두번영택사스가",
  nosferatuHodd = "노스페라투 호드",
  dandap_Bug = "단답벌레",
  dopamine = "도파민박사",
  dokkoHyeji = "독고혜지",
  roentgenium = "뢴트게늄",
  bujungingan = "부정형인간",
  mitsuneHaku = "미츠네 하쿠",
  secretGirl = "비밀소녀",
  businesskim = "비즈니스킴",
  friedshrimp = "새우튀김",
  sophia = "소피아",
  wakphago = "왁파고",
  leeDeokSu = "이덕수 할아바이",
  carnarJungtur = "카르나르 융터르",
  callyCarly = "캘리칼리 데이비슨",
  pungsin = "풍신",
  freeter = "프리터",
  rusuk = "해루석",
  hikiking = "히키킹"
}

export const gomemClassList = ["?", "common", "rare", "epic", "legend"];
